### ISSUE TITLE
QUESTION - why have set/get accessors if the field is public

### ISSUE THREAD

**Issue by skewty** [swaggest/php-code-builder#35]
I am coming from python and looking for something similar to [pydantic](https://pydantic-docs.helpmanual.io/) (perhaps some future inspiration may come from that project used along with FastAPI) and came across this project while reading [StackOverflow](https://stackoverflow.com/questions/16726526/making-a-php-object-from-a-json-schema).

IMO this project looks like a more modern (OpenAPI centric web service) than say `symfony/validator` or `respect/validation`.   Great idea and work people!

My question / concern is that the set / get methods seem silly / wasteful and pointless given the generated fields are public.  Am I missing something?  What is their purpose?  What feature do they add?

**Comment by vearutop** [comment]
Hi, getters and setters are optional and are disabled by default. 

I agree, having getters does not seem to make much sense in presence of public properties, I can think of some exotic use case when application expects getters to use them via reflection.

Setters have a more realistic use case though, they are implemented in fluent syntax (with `return $this`) and can be used to initialize anonymous value, e.g.:
```
doSomething((new User)->setId(1)->setName('Jane'));
```
https://github.com/swaggest/php-code-builder/blob/v0.2.28/tests/src/Tmp/Example/User.php#L57

If there is no need for getters and setters in your case, I suggest to not render them (default behavior, can be changed at https://github.com/swaggest/php-code-builder/blob/v0.2.28/src/JsonSchema/PhpBuilder.php#L48-L49).
