### ISSUE TITLE
const is unsupported

### ISSUE THREAD

**Issue by jmauerhan** [swaggest/php-code-builder#40]
When I have a json schema file with a `const`, the class that is generated by php-code-builder cannot be serialized, when calling the `jsonSerialize` method, I get this error: `Call to undefined method stdClass::out()`. 

It only happens with `const` properties. 

Const was added in draft 6 I believe, so I'm surprised this isn't supported yet. Are there plans to add it?

**Comment by vearutop** [comment]
Thank you for this issue, please try `v0.2.33`.
